export interface ItemSearchCategoryEntry {
  id: number;
  name: string;
  group: 'Weapons' | 'Tools' | 'Armor' | 'Accessories' | 'Medicines & Meals' | 'Materials' | 'Other' | 'Housing';
}

// Pinned from XIVAPI on 2026-05-11. Run the probe in Task 1 if you suspect drift.
export const ITEM_SEARCH_CATEGORIES: ItemSearchCategoryEntry[] = [  { id: 1, name: "Primary Arms", group: "Weapons" },
  { id: 2, name: "Primary Tools", group: "Tools" },
  { id: 3, name: "Primary Tools", group: "Tools" },
  { id: 4, name: "Armor", group: "Armor" },
  { id: 5, name: "Accessories", group: "Other" },
  { id: 6, name: "Medicines", group: "Medicines & Meals" },
  { id: 7, name: "Materials", group: "Materials" },
  { id: 8, name: "Other", group: "Other" },
  { id: 9, name: "Pugilist's Arms", group: "Weapons" },
  { id: 10, name: "Gladiator's Arms", group: "Weapons" },
  { id: 11, name: "Marauder's Arms", group: "Weapons" },
  { id: 12, name: "Archer's Arms", group: "Weapons" },
  { id: 13, name: "Lancer's Arms", group: "Weapons" },
  { id: 14, name: "Thaumaturge's Arms", group: "Weapons" },
  { id: 15, name: "Conjurer's Arms", group: "Weapons" },
  { id: 16, name: "Arcanist's Arms", group: "Weapons" },
  { id: 17, name: "Shields", group: "Weapons" },
  { id: 18, name: "Dancer's Arms", group: "Weapons" },
  { id: 19, name: "Carpenter's Tools", group: "Tools" },
  { id: 20, name: "Blacksmith's Tools", group: "Tools" },
  { id: 21, name: "Armorer's Tools", group: "Armor" },
  { id: 22, name: "Goldsmith's Tools", group: "Tools" },
  { id: 23, name: "Leatherworker's Tools", group: "Materials" },
  { id: 24, name: "Weaver's Tools", group: "Tools" },
  { id: 25, name: "Alchemist's Tools", group: "Tools" },
  { id: 26, name: "Culinarian's Tools", group: "Tools" },
  { id: 27, name: "Miner's Tools", group: "Tools" },
  { id: 28, name: "Botanist's Tools", group: "Tools" },
  { id: 29, name: "Fisher's Tools", group: "Tools" },
  { id: 30, name: "Fishing Tackle", group: "Tools" },
  { id: 31, name: "Head", group: "Armor" },
  { id: 32, name: "Undershirts", group: "Armor" },
  { id: 33, name: "Body", group: "Armor" },
  { id: 34, name: "Undergarments", group: "Armor" },
  { id: 35, name: "Legs", group: "Armor" },
  { id: 36, name: "Hands", group: "Armor" },
  { id: 37, name: "Feet", group: "Armor" },
  { id: 38, name: "Waist", group: "Armor" },
  { id: 39, name: "Necklaces", group: "Accessories" },
  { id: 40, name: "Earrings", group: "Accessories" },
  { id: 41, name: "Bracelets", group: "Accessories" },
  { id: 42, name: "Rings", group: "Accessories" },
  { id: 43, name: "Medicine", group: "Medicines & Meals" },
  { id: 44, name: "Ingredients", group: "Medicines & Meals" },
  { id: 45, name: "Meals", group: "Medicines & Meals" },
  { id: 46, name: "Seafood", group: "Medicines & Meals" },
  { id: 47, name: "Stone", group: "Materials" },
  { id: 48, name: "Metal", group: "Materials" },
  { id: 49, name: "Lumber", group: "Materials" },
  { id: 50, name: "Cloth", group: "Materials" },
  { id: 51, name: "Leather", group: "Materials" },
  { id: 52, name: "Bone", group: "Materials" },
  { id: 53, name: "Reagents", group: "Materials" },
  { id: 54, name: "Dyes", group: "Materials" },
  { id: 55, name: "Weapon Parts", group: "Other" },
  { id: 56, name: "Furnishings", group: "Housing" },
  { id: 57, name: "Materia", group: "Materials" },
  { id: 58, name: "Crystals", group: "Materials" },
  { id: 59, name: "Catalysts", group: "Materials" },
  { id: 60, name: "Miscellany", group: "Other" },
  { id: 61, name: "Soul Crystals", group: "Materials" },
  { id: 62, name: "Arrows", group: "Weapons" },
  { id: 63, name: "Quest Items", group: "Other" },
  { id: 64, name: "Other", group: "Other" },
  { id: 65, name: "Exterior Fixtures", group: "Housing" },
  { id: 66, name: "Interior Fixtures", group: "Housing" },
  { id: 67, name: "Outdoor Furnishings", group: "Housing" },
  { id: 68, name: "Chairs and Beds", group: "Other" },
  { id: 69, name: "Tables", group: "Other" },
  { id: 70, name: "Tabletop", group: "Housing" },
  { id: 71, name: "Wall-mounted", group: "Housing" },
  { id: 72, name: "Rugs", group: "Housing" },
  { id: 73, name: "Rogue's Arms", group: "Weapons" },
  { id: 74, name: "Seasonal Miscellany", group: "Other" },
  { id: 75, name: "Minions", group: "Other" },
  { id: 76, name: "Dark Knight's Arms", group: "Weapons" },
  { id: 77, name: "Machinist's Arms", group: "Weapons" },
  { id: 78, name: "Astrologian's Arms", group: "Weapons" },
  { id: 79, name: "Airship/Submersible Components", group: "Materials" },
  { id: 80, name: "Orchestrion Components", group: "Materials" },
  { id: 81, name: "Gardening Items", group: "Housing" },
  { id: 82, name: "Paintings", group: "Housing" },
  { id: 83, name: "Samurai's Arms", group: "Weapons" },
  { id: 84, name: "Red Mage's Arms", group: "Weapons" },
  { id: 85, name: "Scholar's Arms", group: "Weapons" },
  { id: 86, name: "Gunbreaker's Arms", group: "Weapons" },
  { id: 87, name: "Dancer's Arms", group: "Weapons" },
  { id: 88, name: "Reaper's Arms", group: "Weapons" },
  { id: 89, name: "Sage's Arms", group: "Weapons" },
  { id: 90, name: "Registrable Miscellany", group: "Other" },
  { id: 91, name: "Viper's Arms", group: "Weapons" },
  { id: 92, name: "Pictomancer's Arms", group: "Weapons" },
];

export function categoriesByGroup(group: ItemSearchCategoryEntry['group']): number[] {
  return ITEM_SEARCH_CATEGORIES.filter((c) => c.group === group).map((c) => c.id);
}

export function categoryLabel(id: number): string {
  return ITEM_SEARCH_CATEGORIES.find((c) => c.id === id)?.name ?? `SC ${id}`;
}
